version: '3'
services:
 app:
   container_name: laravel_app
   # 80番ポートのバーチャルホストは000-default.confにて設定済み
   ports:
     - "8000:80"
   build: ./Docker/App
   # Laravelのソースを同期
   volumes:
     - ./src:/var/www/html
 db:
   image: mysql:5.7
   container_name: laravel_db
   # MySQLの環境変数
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: laraveldb
     MYSQL_USER: dbuser
     MYSQL_PASSWORD: dbpass
     TZ: 'Asia/Tokyo'
   # 起動時のコマンド
   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   # DB内容を同期
   volumes:
     - ./Docker/DB/volume:/var/lib/mysql
     - ./Docker/DB/my.cnf:/etc/mysql/conf.d/my.cnf
   ports:
     - 13306:3306
 phpmyadmin:
   container_name: phpmyadmin
   image: phpmyadmin/phpmyadmin
   #phpmyadminの環境変数
   environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=db
    - PMA_USER=root
    - PMA_PASSWORD=root
   ports:
    - 3000:80